# Обработка ошибок

Что такое исключение (exception) в Python?
Как обрабатывать исключения с использованием блока 'try...except'?
Что такое блок 'finally' и когда он используется?
Как создать собственное исключение (exception)?
Как получить информацию об ошибке (exception traceback)?